version: '3.8'

services:
  project: &project
    build:
      context: .
  web:
    <<: *project
    ports:
      - 3000:3000
    command: yarn serve:web
  api:
    <<: *project
    ports:
      - 3100:3100
    command: yarn serve:api
  minio:
    image: minio/minio:latest
    volumes:
      - minio-data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: |
      server
      --address ":9000"
      --console-address ":9001"
      /data

volumes:
  minio-data:
