services:
  web:
    build:
      dockerfile: Dockerfile.web
      target: install
    command: yarn start
    environment:
      CI: ${CI-}
      NODE_ENV: ${NODE_ENV:-development}
      REACT_APP_KEYCLOAK_ADDRESS: http://localhost:8080
    ports:
      - 3000:3000
    volumes:
      - ./web/src:/app/src

  api:
    build:
      dockerfile: Dockerfile.api
      target: install
    command: yarn start
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      CI: ${CI-}
      KEYCLOAK_ADDRESS: http://keycloak:8080
      PG_PASSWORD: ${PG_PASSWORD:?}
      PG_HOST: postgres
      MINIO_HOST: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER:?}
      MINIO_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD:?}
    ports:
      - 3100:3100
    volumes:
      - ./api/src:/app/src
    depends_on:
      - postgres
      - minio

  minio:
    image: minio/minio:latest
    volumes:
      - minio-data:/data
      - ./fixtures/media:/fixtures/media
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:?}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?}
    command: |
      server
      --address ":9000"
      --console-address ":9001"
      /data
  minio-proxy:
    image: caddy
    ports:
      - 9002:9002
    volumes:
      - ./minio.dev.Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - minio

  postgres:
    image: postgres:14
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT_EXPOSED:-5432}:5432
    environment:
      - PGUSER=postgres
      - PGHOST=localhost
      - POSTGRES_DB=verified_by_video
      - POSTGRES_PASSWORD=${PG_PASSWORD:?}

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 8080:8080
    volumes:
      - ./fixtures/keycloak-dev-realm.json:/opt/keycloak/data/import/keycloak-dev-realm.json
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN:?}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:?}
    command: start-dev --import-realm

volumes:
  minio-data:
  postgres-data:
  caddy-data:
  caddy-config:
