FROM node:20 AS install

WORKDIR /app
COPY .yarn/releases .yarn/releases
COPY .yarnrc.yml .yarnrc.yml
COPY web/package.json package.json
RUN corepack enable
RUN yarn install

COPY web .

FROM install AS build

RUN yarn build

FROM caddy:alpine AS production

COPY --from=build /app/build /app/build
COPY web/Caddyfile /etc/caddy/Caddyfile
RUN caddy fmt --overwrite /etc/caddy/Caddyfile

EXPOSE 3000
