name: Test Workflow

on: [push]

jobs:
  tests:
    name: Automated Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      - run: yarn install --immutable
      - run: yarn check-format
      - run: yarn test
